### ISSUE TITLE
Fix quick-start deploy example

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#167]
The _[Developer Quick Start](https://github.com/TOSIT-IO/tdp-lib/blob/master/docs/developer/cli/developer_quick_start.rst)_ documentation page is missing a `--target` flag on the deploy command at step 8, causing the command to fail:

```bash
tdp deploy zookeeper_install --dry
```

**Comment by rpignolet** [comment]
Yes 639f7918a6864df47268f3402b4e5cad6e35ff78 changed the behavior but the doc was not updated.
