### ISSUE TITLE
Component in tdp-lib is ambiguous 

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-lib#169]
We have differents notions of components. Mainly, the class `Component` does not represent a component, but what we use as a target (`service_component_action` <-- this triple, or `service_action` <-- this tuple).

A better name for this class should be `Operation`. Because nodes in the dag define operation to be performed on the cluster.

**Comment by rpignolet** [comment]
`Operation` seems to be a good name for the triple `service_component_action`
