### ISSUE TITLE
restart_required: not supported after tdp_cluster vars change 

### ISSUE THREAD

**Issue by mehdibn** [TOSIT-IO/tdp-lib#236]

**Comment by rpignolet** [comment]
Changing `all.yml` inside `tdp_vars` is not supported too. `all` and `tdp_cluster` "service" are not in the DAG and are not store inside `service_log` table.
We must first consider `all` and `tdp_cluster` as service and store their version inside `service_log` when we deploy.
Then inside `restart-required` commands, handle `all` and `tdp_cluster` service and run without `sources` the `operation_runner.run_nodes()` (i.e. reconfigure and restart all services/components).

**Comment by gboutry** [comment]
After some testing, exporter is missing from restart required

**Comment by gboutry** [comment]
Opened:
- [ ] https://github.com/TOSIT-IO/tdp-collection/pull/611

**Comment by rpignolet** [comment]
@mehdibn this issue is still revelant ?
