### ISSUE TITLE
`tdp init --overiddes` fails if one of the overrides file is empty

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/tdp-lib#324]
Reproduce:
```
tdp init --overrides tdp_vars_overrides
```

If one of the file in the override is empty (e.g. `tdp_vars_overrides/hive/hive.yml`) init crashes with error

```
raise EmptyCommit(
tdp.core.repository.repository.EmptyCommit: validating these changes would produce no difference
```

**Comment by PaulFarault** [comment]
Would it be better to raise an error like `EmptyFile` or to just ignore it?

**Comment by PACordonnier** [comment]
A Warning explicity saying that the file is empty and no commit has been made is appropriate imo
