### ISSUE TITLE
[cli] Move the `playbooks` command to a script

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#346]
The `tdp playbooks` command is used to generate meta playbooks, which are employed for deploying TDP without the necessity of using tdp-lib. We could convert it to a script instead of having it as a command.

The underlying question may be: "what's the purpose of tdp-lib?". Is it made for developers or for users?

**Comment by rpignolet** [comment]
`tdp playbooks` command is for TDP developpers to generate meta playbooks.

**Comment by rpignolet** [comment]
`tdp-lib` commands are for users in order to deploy TDP without the server or without the UI.

**Comment by PaulFarault** [comment]
Ok, so the issue is valid, I'll remove the `tdp playbooks` command.

**Comment by sergkudinov** [comment]
@PaulFarault remove the cli test then, if #350 is merged before

**Comment by PaulFarault** [comment]
I won't do it for now so it's ok.
