### ISSUE TITLE
Deployment plan edition

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#356]
We should add support for CRUD operations on a generated DeploymentPlan. This could be done using either:

- sub-commands (`tdp plan add ...`, `tdp plan remove ...`, etc...).
- interactive mode (`tdp plan edit`), using the `EDITOR` environment variable.

We may want to start with the interactive mode which should offer a better UX.

**Comment by mdrutel** [comment]
Hi,
I suggest the following specs :

  - Editor
We could use the editor set by the environment variable "EDITOR" ; if not set, we could use 'vi'

  - File format
The list of the operations will be saved in a file and displayed in the editor. Each line represents 1 operation.
The file extension could be "tsv" or "csv".

We also could add help in the file, like a list of possible operations in a comment.

  - Steps
    * Load the planned deployment log
    * Save the plan in a temporary file
    * Load the file to the editor
    * Save the modification in the temporary file
    * Read it and store the operations in a list ; empty lines will be removed
    * Create the deployment log
  
  - Tests
    * If there's no change, an exception is raised : "Plan was not modified." ;
    * After the edition, if the plan is empty, an exception is raised : "Plan must not be empty." ;
    * If the plan is modified, the new plan takes the Deployment type "OPERATIONS".

**Comment by PaulFarault** [comment]
- > We could use the editor set by the environment variable "EDITOR"
  
  Shouldn't we tried the `VISUAL` editor first, fall back to `EDITOR` if `VISUAL` is not set, and finally fall back to vi?
  
- > The file extension could be "tsv" or "csv".
  
  TSV looks fine.
  
- I agree with the step you suggested. You miss a test if the operations exists before saving them in the database, but this is already implemented anyway when doing a `DeploymentPlan.from_operations` as you suggested.

**Comment by mdrutel** [comment]
Additional suggestions :
- use of ```EDITOR``` or ```VISUAL``` or ```vi``` as suggested by @PaulFarault 
- One line is for one single operation :
  - on a single host : "[operation] on [host]"
  - on all host : "[operation]"

**Comment by PaulFarault** [comment]
@mdrutel You may also want to include  #389 extra options in plan edition as the PR has been merged since then.
