### ISSUE TITLE
Add command for variable edition

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#360]
Variable edition is currently done manually (file edition then commit). Would be nice to have dedicated commands to do it.

The main reason is because of the new `tdp stale` command(#348). We need a way to track which configurations are edited. Also, it could help us to ensure good commit messages.

The command could open an editor to modify the variable file, then commit it and execute the appropriated hooks.

**Comment by jpsavy** [comment]
Proposal of specifications: 

-      Editor 
         Use the editor defined by the "EDITOR" environment variable; if not defined we will use 'vi' 

-      Steps 
         Load the variables file into the editor 
         Save changes to file 
         Index the file to commit 
         Modify/Validate the message associated with the commit 

-      Command 
         tdp vars edit <relative_path_to_vars_file> 

-      Tests 
         After editing, in case of wrong commit message, an exception is thrown: "The commit message is not in a correct format." 
         If the variable file is modified and the commit message is in the correct format, the modification is committed.

**Comment by PaulFarault** [comment]
I wonder if we should let the user save his variables wherever he wants or if we should manage it ourselves.

Instead of a `<file_path>`, we could pass a `<service_name>` and an optional `<component_name>` as arguments.

**Comment by PaulFarault** [comment]
As discussed on the last contributor meeting, the API should look like: `tdp vars edit <service_name> [<component_name>|<file_path>]` as services are organized by repositories.
