### ISSUE TITLE
`tdp init` fails due to AnsibleJSONDecoder

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/tdp-lib#418]
#399 introduced a bug.

before: we read and parsed a var file using `yaml` module (pyyaml)
now: we read and parsed using `ansible.parsing.utils.yaml`

Problem: the type of the cotnent in python used to be a dict. Now it's a ansible.parsing.yaml.objects.AnsibleMapping. When doing an `tdp init`, we write the contents of the vars to a new file. But since it is not a dictionnary the writing fails

```
        self._file_descriptor.write(
            yaml.dump(self._content, Dumper=Dumper, sort_keys=False, width=1000)
        )
```

**Comment by sergkudinov** [comment]
Can you please provide detailed instruction how to reproduce this?
I do `tdp init` on a clean state and it works without errors.
