### ISSUE TITLE
Extract the log from a deployment and/or operation

### ISSUE THREAD

**Issue by mdrutel** [TOSIT-IO/tdp-lib#445]
Hi,

For now, the only way to have the log of the deployment is to read the console output, or think to redirect the output into a file.
the command ```tdp browse <id>``` only displays the first 20 characters.

It would be nice to be able to export the logs in a file.

**Comment by PaulFarault** [comment]
Are you talking about the Ansible logs which result of the execution of an operation?

If yes, the appropriated command to see the whole log is `tdp browse [id] [operation_name]`. Is it what you were looking for?

**Comment by mdrutel** [comment]
Actually, when I wrote this issue, I didn"t know that there is a command to print the operation log of a given deployment.

This command is what I thought, thanks ^^
