### ISSUE TITLE
Component without start action are not recorded inside ComponentVersionLog

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-lib#447]
To reproduce:

Perform a fresh deployment
```
tdp init
tdp plan dag
tdp deploy
```

Look at service versions:
```
tdp service-versions
```
All `*_client` components are missing.

Only component with start action are recorded inside `ComponentVersionLog` table.

**Comment by PaulFarault** [comment]
This should be fixed by #448, I'll have a look at it.
