### ISSUE TITLE
Optional `--run-directory`

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#488]
On the `tdp deploy` command, the `--run-directory` option is used to define the working directory when spawning a subprocess to execute an Ansible command (using `subprocess.Popen`). If no directory is provided, the subprocess uses the parent process directory.

We made both the `--run-directory` option mandatory on the cli AND the `run_directory` parameter optional on the core. Should we keep this behavior, ensure that the working directory is provided or make it entirely optional?

---

If we choose to keep this behavior, we should at least remove the following condition in the deploy command (as the run_directory is required):

```py
Executor(
    run_directory=run_directory.absolute() if run_directory else None,
    # ...
),
```

**Comment by Pierrotws** [comment]
Having it mandatory doesn't make sense imho.

Also, the standard name for this is cwd (current working directory), that's what I would choose as name.

--run-directory is way too long.

**Comment by Pierrotws** [comment]
That's what is chosen by yarn (package manager) :
```
yarn --cwd ~/test_project/ dev
```

**Comment by PaulFarault** [comment]
Make sense, thanks! I'll make a PR.
