### ISSUE TITLE
Choose between `state` and `status` for logs

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-lib#489]
(`PLANNED`, `RUNNING`, `SUCCESS`, `FAILURE`...) are stored as a `state` for the `OperationLog` and as a `status` for `DeploymentLog`. We should pick one name and stick to it everywhenre.

**Comment by sergkudinov** [comment]
Found some definitions:

- **Status** is one-dimensional, i.e., it is determined by a single value (e.g., the social rank of a person, the amount of progress made by a project, the goodness of an outcome, etc.) usually ranging from good to bad, desirable to undesirable, or the like.

- **State** is “all the rest”: it is either n-dimensional (with n > 1), or it does not refer to something that can be ordered by quality. In practice, though, state is often used when the conditions for using status would apply.

And another one:

- **Status** - a situation at a particular time, especially in an argument, discussion etc.
- **State** - the physical or mental condition that someone or something is in

To me, it is correct to call it `status`. Respectively, `tdp status` is more like `tdp state` in that sense.
